### ISSUE TITLE
empty key clobbers previous keys

### ISSUE THREAD

**Issue by brettmc** [brettmc/docker-compose-generator#14]
eg merging:
```yaml
services:
  foo:
    image: foo
```
with
```yaml
services:
```

will result in:
```yaml
services: null
```
